import type { DashboardSnapshot, TradableAsset } from '@/lib/dashboard/types';

export const mockAssets: TradableAsset[] = [
  { symbol: 'SPY', name: 'SPDR S&P 500 ETF Trust', tradable: true, optionsEnabled: true },
  { symbol: 'QQQ', name: 'Invesco QQQ Trust', tradable: true, optionsEnabled: true },
  { symbol: 'GLD', name: 'SPDR Gold Shares', tradable: true, optionsEnabled: true },
  { symbol: 'AAPL', name: 'Apple Inc.', tradable: true, optionsEnabled: true },
  { symbol: 'MSFT', name: 'Microsoft Corporation', tradable: true, optionsEnabled: true },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', tradable: true, optionsEnabled: true },
];

export const mockSnapshot: DashboardSnapshot = {
  connection: {
    status: 'mock',
    label: 'Alpaca not connected',
    detail: 'Representative paper-account data',
  },
  account: {
    accountNumber: null,
    equity: 100612,
    buyingPower: 96480,
    todayProfitLoss: 192,
    todayProfitLossPercent: 0.19,
    openRisk: 742,
  },
  equityHistory: [
    { date: 'Aug 22', equity: 100000 },
    { date: 'Aug 23', equity: 100120 },
    { date: 'Aug 24', equity: 99940 },
    { date: 'Aug 25', equity: 100310 },
    { date: 'Aug 26', equity: 100180 },
    { date: 'Aug 27', equity: 100420 },
    { date: 'Aug 28', equity: 100612 },
  ],
  openPositions: [
    {
      id: 'mock-gld-call',
      symbol: 'GLD260918C00350000',
      underlying: 'GLD',
      underlyingName: 'Gold',
      optionType: 'call',
      strike: 350,
      expiration: '2026-09-18',
      daysToExpiration: 20,
      quantity: 1,
      averageEntryPrice: 2.1,
      currentPrice: 2.334,
      marketValue: 233.4,
      unrealizedProfitLoss: 23.4,
      unrealizedProfitLossPercent: 0.03,
      lastUpdated: 'Just now',
    },
    {
      id: 'mock-spy-put',
      symbol: 'SPY260911P00760000',
      underlying: 'SPY',
      underlyingName: 'S&P 500',
      optionType: 'put',
      strike: 760,
      expiration: '2026-09-11',
      daysToExpiration: 13,
      quantity: 1,
      averageEntryPrice: 3.42,
      currentPrice: 3.27,
      marketValue: 327,
      unrealizedProfitLoss: -15,
      unrealizedProfitLossPercent: -4.39,
      lastUpdated: 'Just now',
    },
    {
      id: 'mock-qqq-call',
      symbol: 'QQQ260918C00690000',
      underlying: 'QQQ',
      underlyingName: 'Nasdaq 100',
      optionType: 'call',
      strike: 690,
      expiration: '2026-09-18',
      daysToExpiration: 20,
      quantity: 2,
      averageEntryPrice: 1.86,
      currentPrice: 2.04,
      marketValue: 408,
      unrealizedProfitLoss: 36,
      unrealizedProfitLossPercent: 9.68,
      lastUpdated: 'Just now',
    },
  ],
  completedTrades: [
    {
      id: 'mock-trade-1',
      closedAt: '2026-08-28T14:42:00-04:00',
      underlying: 'SPY',
      contract: 'Call · $770 · Sep 04',
      quantity: 1,
      entryPrice: 2.18,
      exitPrice: 2.64,
      profitLoss: 46,
      returnPercent: 21.1,
      status: 'closed',
      report: 'Directional thesis reached its price target before the time-based exit.',
    },
    {
      id: 'mock-trade-2',
      closedAt: '2026-08-27T15:11:00-04:00',
      underlying: 'GLD',
      contract: 'Put · $340 · Sep 11',
      quantity: 1,
      entryPrice: 1.74,
      exitPrice: 1.49,
      profitLoss: -25,
      returnPercent: -14.37,
      status: 'closed',
      report: 'Position closed after the directional thesis was invalidated.',
    },
    {
      id: 'mock-trade-3',
      closedAt: '2026-08-26T13:06:00-04:00',
      underlying: 'QQQ',
      contract: 'Call · $680 · Sep 04',
      quantity: 1,
      entryPrice: 2.92,
      exitPrice: 3.08,
      profitLoss: 16,
      returnPercent: 5.48,
      status: 'closed',
      report: 'Time-based exit completed with a small gain.',
    },
  ],
  updatedAt: new Date().toISOString(),
  isMock: true,
};
